apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exam-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: exam-platform
  app.kubernetes.io/managed-by: kustomize
